[package]
name = "ststracker-base"
version = "0.1.0"
authors = ["Robert Usher <266585+dcchut@users.noreply.github.com>"]
edition = "2018"

[dependencies]
libsts = "0.3.1"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0"