[package]
name = "ststracker-base"
version = "0.1.0"
authors = ["Robert Usher <266585+dcchut@users.noreply.github.com>"]
edition = "2018"

[dependencies]
libsts = "0.1.0"
serde = { version = "1.0", features = ["derive"] }
